CORRECTIONS_R5 = {
    'qmb-all-251': {
        'options_correct': {'A': False, 'B': False, 'C': True, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 8.2.1',
        'isoJustification': 'Kommunikation mit den Kunden muss Informationen in Bezug auf Kundenrückmeldungen einschließlich Reklamationen umfassen.',
        'infobox': 'Transparenz ist im Reklamationsprozess entscheidend, um Vertrauen zu erhalten.',
    },
    'qmb-all-252': {
        'options_correct': {'A': False, 'B': True, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 8.7.1',
        'isoJustification': 'Fehlermanagement befasst sich mit nichtkonformen Ergebnissen, die weitreichende Konsequenzen bis hin zu Sach- und Personenschäden (Produkthaftung) haben können.',
        'infobox': 'Neben internen Kosten deckt Fehlermanagement vor allem auch externe Risiken wie Haftung ab.',
    },
    'qmb-all-253': {
        'options_correct': {'A': False, 'B': True, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.2',
        'isoJustification': 'Reklamationen sind Rückmeldungen zu Fehlern (Nichtkonformitäten), die bereits beim Kunden aufgetreten sind, und lösen den Fehlerbehebungsprozess (CAPA) aus.',
        'infobox': 'Jede Reklamation basiert auf einem Fehler, aber nicht jeder Fehler führt zu einer Reklamation.',
    },
    'qmb-all-254': {
        'options_correct': {'A': False, 'B': True, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9000:2015',
        'isoJustification': 'Das übergeordnete Ziel eines QMS ist es, die Fähigkeit zu demonstrieren, durchgängig Produkte/Dienstleistungen bereitzustellen, die Kundenanforderungen erfüllen.',
        'infobox': 'Das Hauptziel im Qualitätsmanagement ist immer die nachhaltige Kundenzufriedenheit.',
    },
    'qmb-all-255': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.3',
        'isoJustification': 'Kaizen bedeutet "Wandel zum Besseren" und ist die Philosophie der kontinuierlichen, oft kleinschrittigen Verbesserung (KVP).',
        'infobox': 'Kaizen steht für kontinuierliche Verbesserung in kleinen, täglichen Schritten.',
    },
    'qmb-all-256': {
        'options_correct': {'A': False, 'B': True, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.3',
        'isoJustification': 'Die kontinuierliche Verbesserung der Eignung, Angemessenheit und Wirksamkeit des QMS ist ein Grundprinzip der Norm.',
        'infobox': 'KVP ist ein endloser Prozess, der sich auf das gesamte System bezieht.',
    },
    'qmb-all-257': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.3',
        'isoJustification': 'Die Norm fordert explizit die "fortlaufende Verbesserung". KVP ist das methodische Pendant dazu.',
        'infobox': 'Fortlaufende Verbesserung (ISO 10.3) = Kontinuierlicher Verbesserungsprozess (KVP).',
    },
    'qmb-all-258': {
        'options_correct': {'A': False, 'B': True, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 Prinzipien',
        'isoJustification': 'Kundenorientierung und die effiziente Nutzung von Ressourcen (Vermeidung von Verschwendung) sind zentrale QM-Prinzipien.',
        'infobox': 'Lean Management und KVP zielen beide auf Vermeidung von Verschwendung (Muda).',
    },
    'qmb-all-259': {
        'options_correct': {'A': False, 'B': True, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.1',
        'isoJustification': 'Organisationen müssen Chancen zur Verbesserung bestimmen und auswählen.',
        'infobox': 'Der erste Schritt im Verbesserungszyklus ist das Erkennen von Potenzialen.',
    },
    'qmb-all-260': {
        'options_correct': {'A': False, 'B': True, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.2',
        'isoJustification': 'In KVP-Workshops werden Prozesse analysiert, wobei Prozess-Checklisten oder Problemlösungswerkzeuge helfen.',
        'infobox': 'Obwohl SWOT oder Balanced Scorecard nützlich sind, werden im operativen KVP meist Prozesswerkzeuge genutzt.',
    },
    'qmb-all-261': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 7.5',
        'isoJustification': 'Das KVP-Board ist ein Werkzeug zur visuellen Steuerung und Aufrechterhaltung dokumentierter Informationen über Verbesserungsmaßnahmen.',
        'infobox': 'Shopfloor Management nutzt oft KVP-Boards zur Visualisierung.',
    },
    'qmb-all-262': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 7.1.2 & 7.3',
        'isoJustification': 'Einbeziehung der Personen (Engagement of people) ist ein QM-Grundsatz, der durch interaktive Workshops gefördert wird.',
        'infobox': 'KVP lebt von den Ideen und dem Engagement aller Mitarbeitenden.',
    },
    'qmb-all-263': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.3',
        'isoJustification': 'KVP ist ein übergreifendes Konzept zur kontinuierlichen Optimierung von Prozessen und Qualitätssteigerung.',
        'infobox': 'KVP fokussiert sich auf die fortlaufende Optimierung von Prozessen.',
    },
    'qmb-all-264': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9000:2015',
        'isoJustification': 'Wettbewerbsfähigkeit und Kundenzufriedenheit sind die wesentlichen strategischen Ergebnisse eines erfolgreichen QMS und der kontinuierlichen Verbesserung.',
        'infobox': 'Qualität sichert nachhaltig den Markterfolg.',
    },
    'qmb-all-265': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.3',
        'isoJustification': 'Kaizen ist die japanische Philosophie der fortlaufenden Verbesserung in vielen kleinen Schritten durch alle Mitarbeiter.',
        'infobox': 'Stetige kleine Schritte (Kaizen) sind oft erfolgreicher als seltene große Sprünge.',
    },
    'qmb-all-266': {
        'options_correct': {'A': False, 'B': True, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9000:2015 Grundsätze',
        'isoJustification': 'Das Engagement von Personen ("Engagement of people") ist einer der 7 QM-Grundsätze, auf dem KVP basiert.',
        'infobox': 'KVP funktioniert nur, wenn die Mitarbeiter aktiv einbezogen werden.',
    },
    'qmb-all-267': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.2.1',
        'isoJustification': 'Zur Beseitigung der Ursachen von Nichtkonformitäten werden Qualitätswerkzeuge wie das Ishikawa-Diagramm (Fischgrätendiagramm) zur Ursachenanalyse eingesetzt.',
        'infobox': 'Das Ishikawa-Diagramm (Ursache-Wirkungs-Diagramm) analysiert Einflüsse wie Mensch, Maschine, Material etc. (die M-Faktoren).',
    },
    'qmb-all-268': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.2',
        'isoJustification': 'Die 5-Why (5-W) Methode dient zur Ermittlung der wahren Grundursache eines Problems durch wiederholtes Fragen nach dem "Warum".',
        'infobox': 'Frage fünfmal "Warum?", um zur Wurzel des Problems zu gelangen.',
    },
    'qmb-all-269': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 7.5',
        'isoJustification': 'KVP-Boards und Maßnahmenpläne dokumentieren den Fortschritt und Status von Verbesserungen.',
        'infobox': 'Visuelles Management hilft bei der transparenten Steuerung von KVP.',
    },
    'qmb-all-270': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.2',
        'isoJustification': 'KVP-Workshops sind typischerweise Teams, die sich für kurze Zeit zusammensetzen, um spezifische Probleme zu lösen oder Prozesse zu optimieren.',
        'infobox': 'KVP-Workshops konzentrieren sich auf konkrete Problemlösungen in Teamarbeit.',
    },
    'qmb-all-271': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 10.3',
        'isoJustification': 'Kaizen zielt auf die unternehmensweite, stetige Verbesserung ab.',
        'infobox': 'Kaizen betrifft das gesamte Unternehmen und alle Abläufe.',
    },
    'qmb-all-272': {
        'options_correct': {'A': False, 'B': True, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 Einleitung 0.3.2',
        'isoJustification': 'Der PDCA-Zyklus (Plan-Do-Check-Act) ist das zugrundeliegende Prinzip der ISO 9001 zur kontinuierlichen Verbesserung von Prozessen.',
        'infobox': 'Der PDCA-Zyklus ist der Motor des KVP.',
    },
    'qmb-all-273': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9001:2015 9.1.2',
        'isoJustification': 'Die Reklamationsquote ist eine direkte Kennzahl zur Bewertung der Kundenzufriedenheit und Prozessqualität im KVP.',
        'infobox': 'Kennzahlen wie die Reklamationsquote machen Qualitätsverbesserungen messbar.',
    },
    'qmb-all-274': {
        'options_correct': {'A': True, 'B': False, 'C': False, 'D': False},
        'multipleChoice': False,
        'isoClause': 'ISO 9000:2015',
        'isoJustification': 'Wettbewerbsfähigkeit und Kundenzufriedenheit sind Kernziele.',
        'infobox': 'Kundenzufriedenheit steht im Mittelpunkt jedes Qualitätsmanagementsystems.',
    },
}

# The remaining questions 275-368 are broken sentence fragments from a PDF/script.
for i in range(275, 369):
    q_id = f'qmb-all-{i}'
    CORRECTIONS_R5[q_id] = {
        'isBroken': True,
        'options_correct': {},
        'multipleChoice': False,
        'isoClause': '',
        'isoJustification': 'Frage ist ein unvollständiges Satzfragment aus einem PDF-Import und nicht lösbar.',
        'infobox': 'Diese Frage wurde aufgrund mangelnder Qualität aussortiert.'
    }
